In [66]:
import pandas as pd
import mysql.connector
from datetime import datetime

In [2]:
conn = mysql.connector.connect(
    host='localhost',
    user='root',           
    password='YOUR PASSWORD HERE',  
    database='gov_contracts'
)

In [17]:
cursor = conn.cursor()

In [4]:
df = pd.read_csv('cleaned_contracts.csv')

In [5]:
df.shape

(774934, 32)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 774934 entries, 0 to 774933
Data columns (total 32 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   contract_award_unique_key                  774934 non-null  str
 1   award_id_piid                              774934 non-null  str
 2   federal_action_obligation                  774934 non-null  float64
 3   total_dollars_obligated                    774934 non-null  float64
 4   action_date                                774934 non-null  str
 5   action_date_fiscal_year                    774934 non-null  int64
 6   period_of_performance_start_date           774934 non-null  str
 7   period_of_performance_current_end_date     774702 non-null  str
 8   transaction_description                    774923 non-null  str
 9   award_type                                 774702 non-null  str
 10  type_of_contract_pricing                   774934 non-null  str
 11  extent_competed                            774934 non-null  str
 12  number_of_offers_received                  228234 non-null  float64
 13  awarding_agency_name                       774934 non-null  str
 14  awarding_sub_agency_name                   774934 non-null  str
 15  funding_agency_name                        774934 non-null  str
 16  recipient_uei                              774934 non-null  str
 17  recipient_name                             774934 non-null  str
 18  recipient_city_name                        774934 non-null  str
 19  recipient_state_name                       769472 non-null  str
 20  recipient_country_name                     774934 non-null  str
 21  primary_place_of_performance_city_name     758466 non-null  str
 22  primary_place_of_performance_state_name    758481 non-null  str
 23  primary_place_of_performance_country_name  774702 non-null  str
 24  naics_code                                 774934 non-null  float64
 25  naics_description                          774934 non-null  str
 26  product_or_service_code                    774934 non-null  str
 27  product_or_service_code_description        774934 non-null  str
 28  veteran_owned_business                     774934 non-null  str
 29  woman_owned_business                       774934 non-null  str
 30  minority_owned_business                    774934 non-null  str
 31  small_disadvantaged_business               774934 non-null  str
dtypes: float64(4), int64(1), str(27)
memory usage: 189.2 MB

In [7]:
df.head()

,contract_award_unique_key,award_id_piid,federal_action_obligation,total_dollars_obligated,action_date,action_date_fiscal_year,period_of_performance_start_date,period_of_performance_current_end_date,transaction_description,award_type,...,primary_place_of_performance_state_name,primary_place_of_performance_country_name,naics_code,naics_description,product_or_service_code,product_or_service_code_description,veteran_owned_business,woman_owned_business,minority_owned_business,small_disadvantaged_business
0,CONT_AWD_70Z03826PF0000382_7008_-NONE-_-NONE-,70Z03826PF0000382,8525.70,8525.70,2026-06-04,2026,2026-06-04,2027-08-28,"PROCUREMENT OF SPARE ROD, BALL BEARING TO BE U...",PURCHASE ORDER,...,TEXAS,UNITED STATES,336413.0,OTHER AIRCRAFT PARTS AND AUXILIARY EQUIPMENT M...,3110,"BEARINGS, ANTIFRICTION, UNMOUNTED",f,f,f,f
1,CONT_AWD_70B06C26F00000124_7014_70B06C24A00000...,70B06C26F00000124,210405.60,3013141.30,2026-06-04,2026,2026-05-19,2027-05-18,THE PURPOSE OF THIS MODIFICATION IS TO INCORPO...,BPA CALL,...,VIRGINIA,UNITED STATES,541611.0,ADMINISTRATIVE MANAGEMENT AND GENERAL MANAGEME...,R425,SUPPORT- PROFESSIONAL: ENGINEERING/TECHNICAL,f,f,f,f
2,CONT_AWD_47PD5426F0168_4740_47PG5226A0007_4740,47PD5426F0168,47750.07,47750.07,2026-06-04,2026,2026-06-04,2026-09-01,UST SECONDARY LEAK CONTAINMENT REPAIR RICHMOND...,BPA CALL,...,CALIFORNIA,UNITED STATES,541690.0,OTHER SCIENTIFIC AND TECHNICAL CONSULTING SERV...,Z1AA,MAINTENANCE OF OFFICE BUILDINGS,f,f,t,f
3,CONT_AWD_36C24526P0440_3600_-NONE-_-NONE-,36C24526P0440,26787.52,26787.52,2026-06-04,2026,2026-06-08,2026-06-08,BILL ONLY DISPOSABLES UTILIZED DURING PATIENT ...,PURCHASE ORDER,...,MICHIGAN,UNITED STATES,339112.0,SURGICAL AND MEDICAL INSTRUMENT MANUFACTURING,6515,"MEDICAL AND SURGICAL INSTRUMENTS, EQUIPMENT, A...",t,f,f,f
4,CONT_AWD_15B20726F00000108_1540_36W79720D0001_...,15B20726F00000108,15088.68,15088.68,2026-06-04,2026,2026-06-04,2026-06-04,MCKESSON DRUGS MEDICATIONS CONTRACT # 36W79720...,DELIVERY ORDER,...,TEXAS,UNITED STATES,325412.0,PHARMACEUTICAL PREPARATION MANUFACTURING,6505,DRUGS AND BIOLOGICALS,f,f,f,f

In [40]:
df.isnull().sum()

contract_award_unique_key                         0
award_id_piid                                     0
federal_action_obligation                         0
total_dollars_obligated                           0
action_date                                       0
action_date_fiscal_year                           0
period_of_performance_start_date                  0
period_of_performance_current_end_date          232
transaction_description                          11
award_type                                      232
type_of_contract_pricing                          0
extent_competed                                   0
number_of_offers_received                    546700
awarding_agency_name                              0
awarding_sub_agency_name                          0
funding_agency_name                               0
recipient_uei                                     0
recipient_name                                    0
recipient_city_name                               0
recipient_state_name                           5462
recipient_country_name                            0
primary_place_of_performance_city_name        16468
primary_place_of_performance_state_name       16453
primary_place_of_performance_country_name       232
naics_code                                        0
naics_description                                 0
product_or_service_code                           0
product_or_service_code_description               0
veteran_owned_business                            0
woman_owned_business                              0
minority_owned_business                           0
small_disadvantaged_business                      0
dtype: int64

In [9]:
df.columns.tolist()

['contract_award_unique_key',
 'award_id_piid',
 'federal_action_obligation',
 'total_dollars_obligated',
 'action_date',
 'action_date_fiscal_year',
 'period_of_performance_start_date',
 'period_of_performance_current_end_date',
 'transaction_description',
 'award_type',
 'type_of_contract_pricing',
 'extent_competed',
 'number_of_offers_received',
 'awarding_agency_name',
 'awarding_sub_agency_name',
 'funding_agency_name',
 'recipient_uei',
 'recipient_name',
 'recipient_city_name',
 'recipient_state_name',
 'recipient_country_name',
 'primary_place_of_performance_city_name',
 'primary_place_of_performance_state_name',
 'primary_place_of_performance_country_name',
 'naics_code',
 'naics_description',
 'product_or_service_code',
 'product_or_service_code_description',
 'veteran_owned_business',
 'woman_owned_business',
 'minority_owned_business',
 'small_disadvantaged_business']

In [10]:
## AGENCY TABLE

agency_cols = ['awarding_agency_name', 'awarding_sub_agency_name', 'funding_agency_name']

In [11]:
agency_df = df[agency_cols].drop_duplicates()

In [12]:
agency_df

,awarding_agency_name,awarding_sub_agency_name,funding_agency_name
0,Department of Homeland Security,U.S. Coast Guard,Department of Homeland Security
1,Department of Homeland Security,U.S. Customs and Border Protection,Department of Homeland Security
2,General Services Administration,Public Buildings Service,General Services Administration
3,Department of Veterans Affairs,Department of Veterans Affairs,Department of Veterans Affairs
4,Department of Justice,Federal Prison System / Bureau of Prisons,Department of Justice
...,...,...,...
522834,Department of Defense,Defense Information Systems Agency,Nuclear Regulatory Commission
590631,General Services Administration,Federal Acquisition Service,Office of Government Ethics
665030,General Services Administration,Federal Acquisition Service,Pension Benefit Guaranty Corporation
725875,General Services Administration,Public Buildings Service,Court Services and Offender Supervision Agency
731936,Department of Defense,Defense Information Systems Agency,National Archives and Records Administration

In [14]:
agency_map = {}

In [18]:
for _, row in agency_df.iterrows():
    cursor.execute(""" INSERT INTO agencies(awarding_agency_name, awarding_sub_agency_name, funding_agency_name)
                        VALUES(%s, %s, %s)""",
                  (row['awarding_agency_name'],
                  row['awarding_sub_agency_name'],
                  row['funding_agency_name']))
    agency_id = cursor.lastrowid
    agency_map[(row['awarding_agency_name'],
                row['awarding_sub_agency_name'],
                row['funding_agency_name'])] = agency_id

In [19]:
conn.commit()

In [20]:
len(agency_map)

124

In [21]:
## RECIPIENTS

recipients_cols = ["recipient_uei", "recipient_name", "recipient_city_name", "recipient_state_name", "recipient_country_name", 
                   "veteran_owned_business", "woman_owned_business", "minority_owned_business", "small_disadvantaged_business"]

In [26]:
recipients_df = df[recipients_cols].drop_duplicates()

In [39]:
recipients_df

,recipient_uei,recipient_name,recipient_city_name,recipient_state_name,recipient_country_name,veteran_owned_business,woman_owned_business,minority_owned_business,small_disadvantaged_business
0,LAD2HL1R71Z3,"AIRBUS HELICOPTERS, INC.",GRAND PRAIRIE,TEXAS,UNITED STATES,f,f,f,f
1,CKV2L9GZKJK3,DELOITTE CONSULTING LLP,ARLINGTON,VIRGINIA,UNITED STATES,f,f,f,f
2,WX6XFTXM1EM6,"PUNDIR GROUP, INC",SACRAMENTO,CALIFORNIA,UNITED STATES,f,f,t,f
3,RM64EJ3CJ7Z5,"ALLIANT ENTERPRISES, LLC",GRAND RAPIDS,MICHIGAN,UNITED STATES,t,f,f,f
4,S1RUKWWRYFL6,MCKESSON CORPORATION,IRVING,TEXAS,UNITED STATES,f,f,f,f
...,...,...,...,...,...,...,...,...,...
774836,ED6BJKJC9TK1,PHRONESIS GLOBAL TRAINING SOLUTIONS LLC,HOLLYWOOD,SOUTH CAROLINA,UNITED STATES,t,t,f,f
774859,YJ9NUKN4BQ91,MNS KJE JV INC.,SYRACUSE,NEW YORK,UNITED STATES,f,f,t,f
774869,VDXZU4J88SL5,ENCORE HOLDINGS LLC,PAWTUCKET,RHODE ISLAND,UNITED STATES,f,f,f,f
774884,XJ66HYUP9NZ5,"EXIT 123C, LLC",CALABASAS,CALIFORNIA,UNITED STATES,f,t,f,f
774895,J5BMECU7SYJ5,"NEWBRIDGE PARTNERS, INC.",HERNDON,VIRGINIA,UNITED STATES,f,t,f,f

In [36]:
recipients_map = {}

for _, row in recipients_df.iterrows():
    cursor.execute("""INSERT INTO recipients(recipient_uei, recipient_name, recipient_city_name, recipient_state_name, 
    recipient_country_name, veteran_owned_business, woman_owned_business, minority_owned_business, small_disadvantaged_business)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)""",
    (row['recipient_uei'] if pd.notna(row['recipient_uei']) else None,
     row['recipient_name'] if pd.notna(row['recipient_name']) else None,
     row['recipient_city_name'] if pd.notna(row['recipient_city_name']) else None,
     row['recipient_state_name'] if pd.notna(row['recipient_state_name']) else None,
     row['recipient_country_name'] if pd.notna(row['recipient_country_name']) else None,
     row['veteran_owned_business'] if pd.notna(row['veteran_owned_business']) else None,
     row['woman_owned_business'] if pd.notna(row['woman_owned_business']) else None,
     row['minority_owned_business'] if pd.notna(row['minority_owned_business']) else None,
     row['small_disadvantaged_business'] if pd.notna(row['small_disadvantaged_business']) else None))


    recipients_map[row['recipient_uei']] = cursor.lastrowid

In [37]:
conn.commit()

In [38]:
len(recipients_map)

19900

In [42]:
df.columns

Index(['contract_award_unique_key', 'award_id_piid',
       'federal_action_obligation', 'total_dollars_obligated', 'action_date',
       'action_date_fiscal_year', 'period_of_performance_start_date',
       'period_of_performance_current_end_date', 'transaction_description',
       'award_type', 'type_of_contract_pricing', 'extent_competed',
       'number_of_offers_received', 'awarding_agency_name',
       'awarding_sub_agency_name', 'funding_agency_name', 'recipient_uei',
       'recipient_name', 'recipient_city_name', 'recipient_state_name',
       'recipient_country_name', 'primary_place_of_performance_city_name',
       'primary_place_of_performance_state_name',
       'primary_place_of_performance_country_name', 'naics_code',
       'naics_description', 'product_or_service_code',
       'product_or_service_code_description', 'veteran_owned_business',
       'woman_owned_business', 'minority_owned_business',
       'small_disadvantaged_business'],
      dtype='str')

In [49]:
## LOCATIONS

recipient_locs = df[['recipient_city_name', 'recipient_state_name', 'recipient_country_name']]
recipient_locs.columns = ['city_name', 'state_name', 'country_name']
recipient_locs['location_type'] = 'recipient'

In [50]:
recipient_locs

            city_name  state_name   country_name location_type
0       GRAND PRAIRIE       TEXAS  UNITED STATES     recipient
1           ARLINGTON    VIRGINIA  UNITED STATES     recipient
2          SACRAMENTO  CALIFORNIA  UNITED STATES     recipient
3        GRAND RAPIDS    MICHIGAN  UNITED STATES     recipient
4              IRVING       TEXAS  UNITED STATES     recipient
...               ...         ...            ...           ...
774929   MOUNT VERNON  WASHINGTON  UNITED STATES     recipient
774930        HOUSTON       TEXAS  UNITED STATES     recipient
774931       VINELAND  NEW JERSEY  UNITED STATES     recipient
774932       VINELAND  NEW JERSEY  UNITED STATES     recipient
774933         DURHAM  CALIFORNIA  UNITED STATES     recipient

[774934 rows x 4 columns]

In [51]:
performance_locs = df[['primary_place_of_performance_city_name','primary_place_of_performance_state_name',
                       'primary_place_of_performance_country_name']]
performance_locs.columns = ['city_name', 'state_name', 'country_name']
performance_locs['location_type'] = 'performance'

In [52]:
performance_locs

            city_name  state_name   country_name location_type
0       GRAND PRAIRIE       TEXAS  UNITED STATES   performance
1           ARLINGTON    VIRGINIA  UNITED STATES   performance
2            RICHMOND  CALIFORNIA  UNITED STATES   performance
3        GRAND RAPIDS    MICHIGAN  UNITED STATES   performance
4              IRVING       TEXAS  UNITED STATES   performance
...               ...         ...            ...           ...
774929   MOUNT VERNON  WASHINGTON  UNITED STATES   performance
774930        HOUSTON       TEXAS  UNITED STATES   performance
774931       VINELAND  NEW JERSEY  UNITED STATES   performance
774932       VINELAND  NEW JERSEY  UNITED STATES   performance
774933         DURHAM  CALIFORNIA  UNITED STATES   performance

[774934 rows x 4 columns]

In [57]:
locs_df = pd.concat([recipient_locs, performance_locs]).drop_duplicates()

In [61]:
locs_df

            city_name     state_name   country_name location_type
0       GRAND PRAIRIE          TEXAS  UNITED STATES     recipient
1           ARLINGTON       VIRGINIA  UNITED STATES     recipient
2          SACRAMENTO     CALIFORNIA  UNITED STATES     recipient
3        GRAND RAPIDS       MICHIGAN  UNITED STATES     recipient
4              IRVING          TEXAS  UNITED STATES     recipient
...               ...            ...            ...           ...
771743       HOMEWOOD       ILLINOIS  UNITED STATES   performance
772752    LONG VALLEY     NEW JERSEY  UNITED STATES   performance
774268      GREENWOOD        INDIANA  UNITED STATES   performance
774783         AMELIA           OHIO  UNITED STATES   performance
774814      WATERTOWN  MASSACHUSETTS  UNITED STATES   performance

[10157 rows x 4 columns]

In [58]:
locs_map = {}

for _, row in locs_df.iterrows():
    cursor.execute("""INSERT INTO locations(city_name, state_name, country_name, location_type)
    VALUES(%s, %s, %s, %s)""",(
        row['city_name'] if pd.notna(row['city_name']) else None,
        row['state_name'] if pd.notna(row['state_name']) else None,
        row['country_name'] if pd.notna(row['country_name']) else None,
        row['location_type']
    ))

    locs_map[(row['city_name'],
             row['state_name'],
             row['country_name'],
             row['location_type'])] = cursor.lastrowid

In [59]:
conn.commit()

In [60]:
len(locs_map)

10157

In [62]:
df.head()

,contract_award_unique_key,award_id_piid,federal_action_obligation,total_dollars_obligated,action_date,action_date_fiscal_year,period_of_performance_start_date,period_of_performance_current_end_date,transaction_description,award_type,...,primary_place_of_performance_state_name,primary_place_of_performance_country_name,naics_code,naics_description,product_or_service_code,product_or_service_code_description,veteran_owned_business,woman_owned_business,minority_owned_business,small_disadvantaged_business
0,CONT_AWD_70Z03826PF0000382_7008_-NONE-_-NONE-,70Z03826PF0000382,8525.70,8525.70,2026-06-04,2026,2026-06-04,2027-08-28,"PROCUREMENT OF SPARE ROD, BALL BEARING TO BE U...",PURCHASE ORDER,...,TEXAS,UNITED STATES,336413.0,OTHER AIRCRAFT PARTS AND AUXILIARY EQUIPMENT M...,3110,"BEARINGS, ANTIFRICTION, UNMOUNTED",f,f,f,f
1,CONT_AWD_70B06C26F00000124_7014_70B06C24A00000...,70B06C26F00000124,210405.60,3013141.30,2026-06-04,2026,2026-05-19,2027-05-18,THE PURPOSE OF THIS MODIFICATION IS TO INCORPO...,BPA CALL,...,VIRGINIA,UNITED STATES,541611.0,ADMINISTRATIVE MANAGEMENT AND GENERAL MANAGEME...,R425,SUPPORT- PROFESSIONAL: ENGINEERING/TECHNICAL,f,f,f,f
2,CONT_AWD_47PD5426F0168_4740_47PG5226A0007_4740,47PD5426F0168,47750.07,47750.07,2026-06-04,2026,2026-06-04,2026-09-01,UST SECONDARY LEAK CONTAINMENT REPAIR RICHMOND...,BPA CALL,...,CALIFORNIA,UNITED STATES,541690.0,OTHER SCIENTIFIC AND TECHNICAL CONSULTING SERV...,Z1AA,MAINTENANCE OF OFFICE BUILDINGS,f,f,t,f
3,CONT_AWD_36C24526P0440_3600_-NONE-_-NONE-,36C24526P0440,26787.52,26787.52,2026-06-04,2026,2026-06-08,2026-06-08,BILL ONLY DISPOSABLES UTILIZED DURING PATIENT ...,PURCHASE ORDER,...,MICHIGAN,UNITED STATES,339112.0,SURGICAL AND MEDICAL INSTRUMENT MANUFACTURING,6515,"MEDICAL AND SURGICAL INSTRUMENTS, EQUIPMENT, A...",t,f,f,f
4,CONT_AWD_15B20726F00000108_1540_36W79720D0001_...,15B20726F00000108,15088.68,15088.68,2026-06-04,2026,2026-06-04,2026-06-04,MCKESSON DRUGS MEDICATIONS CONTRACT # 36W79720...,DELIVERY ORDER,...,TEXAS,UNITED STATES,325412.0,PHARMACEUTICAL PREPARATION MANUFACTURING,6505,DRUGS AND BIOLOGICALS,f,f,f,f

In [75]:
df['period_of_performance_start_date'].unique().tolist()

['2026-06-04',
 '2026-05-19',
 '2026-06-08',
 '2025-06-01',
 '2025-07-01',
 '2025-08-15',
 '2026-06-05',
 '2026-06-26',
 '2023-09-08',
 '2026-01-13',
 '2026-06-10',
 '2022-09-25',
 '2026-04-28',
 '2026-05-08',
 '2026-05-01',
 '2026-08-01',
 '2024-07-03',
 '2026-01-08',
 '2025-08-04',
 '2024-10-01',
 '2026-06-20',
 '2026-06-03',
 '2026-02-24',
 '2025-08-07',
 '2025-03-14',
 '2024-04-01',
 '2023-08-25',
 '2025-09-30',
 '2026-03-17',
 '2020-10-01',
 '2022-09-09',
 '2025-09-15',
 '2026-09-30',
 '2023-03-20',
 '2026-05-20',
 '2025-10-27',
 '2022-07-01',
 '2026-06-24',
 '2024-10-25',
 '2022-07-20',
 '2026-06-15',
 '2026-02-16',
 '2022-01-26',
 '2025-12-09',
 '2026-07-06',
 '2026-04-01',
 '2025-07-02',
 '2026-01-01',
 '2024-09-20',
 '2026-07-01',
 '2023-08-01',
 '2024-03-06',
 '2024-05-01',
 '2024-07-01',
 '2025-09-01',
 '2025-06-16',
 '2026-05-18',
 '2026-06-01',
 '2026-03-01',
 '2025-10-01',
 '2022-06-07',
 '2026-03-19',
 '2025-09-18',
 '2023-08-29',
 '2025-08-31',
 '2025-09-24',
 '2026-09-04',
 '2025-09-25',
 '2022-09-26',
 '2026-06-22',
 '2026-08-18',
 '2026-08-19',
 '2025-04-15',
 '2026-05-05',
 '2024-09-15',
 '2026-06-16',
 '2021-03-16',
 '2026-06-02',
 '2026-04-30',
 '2025-05-15',
 '2025-01-15',
 '2024-09-27',
 '2025-10-17',
 '2022-07-03',
 '2023-07-01',
 '2024-08-14',
 '2023-06-02',
 '2020-05-01',
 '2023-06-12',
 '2026-03-15',
 '2025-12-10',
 '2025-12-12',
 '2026-05-15',
 '2023-06-01',
 '2024-04-08',
 '2026-09-08',
 '2023-06-22',
 '2025-12-01',
 '2023-12-25',
 '2024-08-01',
 '2022-05-20',
 '2024-06-04',
 '2022-09-30',
 '2026-05-29',
 '2024-07-18',
 '2026-03-11',
 '2024-05-17',
 '2026-05-04',
 '2025-03-01',
 '2021-12-05',
 '2025-06-09',
 '2025-02-14',
 '2026-05-02',
 '2026-07-23',
 '2026-05-06',
 '2023-09-22',
 '2026-09-24',
 '2026-02-04',
 '2024-07-16',
 '2025-08-26',
 '2025-09-19',
 '2022-08-01',
 '2025-06-14',
 '2025-03-18',
 '2023-06-15',
 '2026-03-26',
 '2026-06-30',
 '2024-03-05',
 '2023-10-01',
 '2022-08-24',
 '2024-06-27',
 '2023-05-19',
 '2025-06-07',
 '2026-04-09',
 '2024-09-30',
 '2026-06-11',
 '2024-12-01',
 '2024-07-15',
 '2025-08-08',
 '2026-07-31',
 '2025-12-03',
 '2025-08-01',
 '2025-04-01',
 '2026-03-27',
 '2024-05-16',
 '2024-09-09',
 '2021-10-01',
 '2026-08-22',
 '2024-06-22',
 '2022-09-01',
 '2023-07-20',
 '2023-06-04',
 '2024-06-26',
 '2026-05-28',
 '2025-09-29',
 '2026-04-10',
 '2021-12-06',
 '2026-01-20',
 '2026-01-17',
 '2025-01-01',
 '2026-08-31',
 '2026-03-31',
 '2023-04-14',
 '2021-03-01',
 '2026-02-01',
 '2022-09-12',
 '2026-06-12',
 '2026-07-13',
 '2022-12-21',
 '2026-03-06',
 '2023-09-01',
 '2023-08-15',
 '2023-12-01',
 '2025-05-08',
 '2026-08-30',
 '2025-08-16',
 '2024-07-26',
 '2024-09-01',
 '2022-08-23',
 '2026-08-13',
 '2023-10-17',
 '2022-03-18',
 '2026-08-27',
 '2021-05-01',
 '2026-01-07',
 '2026-04-22',
 '2025-04-14',
 '2026-02-03',
 '2025-01-07',
 '2024-03-07',
 '2026-06-07',
 '2022-04-01',
 '2023-08-21',
 '2024-09-29',
 '2024-09-18',
 '2026-06-18',
 '2026-01-27',
 '2025-10-25',
 '2026-04-24',
 '2020-09-01',
 '2026-05-14',
 '2024-10-14',
 '2026-06-19',
 '2025-09-11',
 '2025-12-19',
 '2023-07-06',
 '2024-02-03',
 '2023-09-28',
 '2026-07-27',
 '2024-08-29',
 '2024-06-05',
 '2022-07-25',
 '2026-04-06',
 '2021-07-29',
 '2025-05-01',
 '2022-09-16',
 '2023-12-18',
 '2025-07-23',
 '2025-06-30',
 '2026-04-03',
 '2025-10-07',
 '2025-08-27',
 '2025-03-07',
 '2025-06-06',
 '2025-02-01',
 '2026-05-26',
 '2026-05-25',
 '2021-09-30',
 '2022-07-22',
 '2026-05-22',
 '2026-06-09',
 '2025-10-13',
 '2026-07-17',
 '2026-07-12',
 '2023-03-01',
 '2021-12-03',
 '2023-06-29',
 '2025-12-02',
 '2026-03-30',
 '2023-04-05',
 '2021-03-02',
 '2025-11-10',
 '2025-08-18',
 '2025-09-22',
 '2026-03-24',
 '2023-07-15',
 '2022-09-14',
 '2024-08-10',
 '2021-02-04',
 '2024-09-23',
 '2026-09-01',
 '2026-03-12',
 '2024-06-10',
 '2025-12-16',
 '2026-08-16',
 '2022-06-12',
 '2026-04-17',
 '2026-12-15',
 '2023-03-02',
 '2024-09-28',
 '2024-06-21',
 '2026-07-20',
 '2022-06-22',
 '2025-06-04',
 '2023-09-29',
 '2022-10-01',
 '2026-07-16',
 '2024-07-22',
 '2026-07-21',
 '2025-08-05',
 '2026-06-17',
 '2025-05-20',
 '2021-07-01',
 '2025-07-11',
 '2025-03-19',
 '2026-09-03',
 '2026-05-27',
 '2025-03-10',
 '2024-06-03',
 '2024-02-28',
 '2025-12-15',
 '2025-12-04',
 '2021-04-05',
 '2026-02-26',
 '2023-08-31',
 '2025-09-04',
 '2023-01-01',
 '2021-09-28',
 '2024-06-01',
 '2026-03-10',
 '2026-01-09',
 '2022-03-09',
 '2024-05-08',
 '2026-08-17',
 '2026-07-26',
 '2024-12-16',
 '2025-09-28',
 '2023-05-11',
 '2026-07-22',
 '2025-07-21',
 '2025-11-01',
 '2024-09-16',
 '2021-08-11',
 '2025-11-04',
 '2025-08-20',
 '2026-04-20',
 '2024-06-14',
 '2024-07-27',
 '2022-09-02',
 '2013-05-28',
 '2020-08-14',
 '2023-09-14',
 '2025-04-25',
 '2025-09-08',
 '2021-09-01',
 '2025-06-12',
 '2025-08-06',
 '2025-10-31',
 '2025-07-29',
 '2025-07-10',
 '2023-09-20',
 '2025-07-24',
 '2024-09-13',
 '2024-03-01',
 '2021-04-01',
 '2026-08-11',
 '2025-07-09',
 '2024-12-23',
 '2026-11-18',
 '2025-05-28',
 '2022-08-15',
 '2026-06-23',
 '2022-02-01',
 '2025-07-30',
 '2026-07-11',
 '2026-06-29',
 '2026-01-16',
 '2024-12-14',
 '2025-11-26',
 '2025-07-31',
 '2026-05-09',
 '2025-04-24',
 '2024-06-15',
 '2022-07-08',
 '2025-05-14',
 '2024-04-23',
 '2021-08-26',
 '2023-04-01',
 '2024-02-02',
 '2025-07-16',
 '2025-06-22',
 '2026-08-09',
 '2023-09-26',
 '2025-07-25',
 '2025-04-29',
 '2023-11-15',
 '2022-02-28',
 '2023-04-03',
 '2026-01-28',
 '2024-06-25',
 '2023-07-19',
 '2025-01-08',
 '2026-08-25',
 '2023-08-14',
 '2025-07-07',
 '2022-05-23',
 '2026-01-26',
 '2025-09-02',
 '2022-06-16',
 '2023-10-30',
 '2023-02-01',
 '2022-05-26',
 '2026-05-11',
 '2026-04-15',
 '2026-03-03',
 '2024-08-15',
 '2024-07-23',
 '2024-08-13',
 '2026-04-08',
 '2024-05-15',
 '2023-03-29',
 '2023-04-12',
 '2026-05-24',
 '2024-07-08',
 '2023-05-12',
 '2026-07-03',
 '2025-03-27',
 '2025-06-05',
 '2026-07-14',
 '2026-04-02',
 '2025-10-15',
 '2025-06-13',
 '2021-07-28',
 '2019-09-25',
 '2023-07-10',
 '2026-08-10',
 '2021-09-27',
 '2021-06-13',
 '2020-03-09',
 '2025-05-27',
 '2024-07-19',
 '2021-06-14',
 '2025-07-08',
 '2025-06-23',
 '2024-06-28',
 '2023-08-22',
 '2024-11-25',
 '2022-06-15',
 '2024-12-03',
 '2026-08-05',
 '2021-09-16',
 '2022-07-06',
 '2026-04-14',
 '2022-11-16',
 '2026-03-13',
 '2020-03-05',
 '2023-01-27',
 '2026-02-18',
 '2026-09-02',
 '2022-04-06',
 '2026-02-05',
 '2026-09-13',
 '2026-07-09',
 '2025-12-11',
 '2025-12-29',
 '2025-03-17',
 '2024-09-26',
 '2010-03-30',
 '2026-04-13',
 '2023-08-10',
 '2025-09-05',
 '2023-06-16',
 '2024-01-18',
 '2021-03-15',
 '2026-08-02',
 '2025-09-03',
 '2025-12-23',
 '2024-12-06',
 '2023-12-12',
 '2025-04-03',
 '2021-03-26',
 '2024-09-03',
 '2025-04-07',
 '2026-07-02',
 '2023-06-24',
 '2023-07-18',
 '2024-04-28',
 '2026-03-20',
 '2025-07-17',
 '2021-04-15',
 '2024-06-12',
 '2027-03-28',
 '2020-10-08',
 '2025-08-11',
 '2024-07-24',
 '2022-09-23',
 '2026-06-13',
 '2023-09-15',
 '2022-03-23',
 '2026-02-12',
 '2026-02-13',
 '2021-10-18',
 '2025-07-26',
 '2021-08-01',
 '2024-06-07',
 '2023-09-30',
 '2025-02-12',
 '2026-04-07',
 '2024-08-26',
 '2026-06-06',
 '2025-09-26',
 '2022-09-15',
 '2025-10-23',
 '2025-09-12',
 '2022-06-01',
 '2024-08-22',
 '2023-04-17',
 '2024-06-18',
 '2024-09-06',
 '2024-01-01',
 '2026-04-27',
 '2021-06-01',
 '2026-10-01',
 '2026-08-03',
 '2025-06-21',
 '2023-05-01',
 '2023-06-25',
 '2025-11-25',
 '2022-06-02',
 '2026-05-21',
 '2022-05-02',
 '2025-03-20',
 '2025-12-18',
 '2023-07-07',
 '2025-05-16',
 '2024-07-02',
 '2021-01-28',
 '2022-10-17',
 '2022-08-26',
 '2025-04-17',
 '2025-10-28',
 '2025-06-02',
 '2022-07-15',
 '2024-07-20',
 '2020-01-01',
 '2019-11-01',
 '2026-09-06',
 '2026-03-25',
 '2022-03-21',
 '2025-09-23',
 '2026-07-29',
 '2026-08-24',
 '2024-05-03',
 '2017-09-25',
 '2025-02-03',
 '2025-04-22',
 '2024-11-04',
 '2025-11-15',
 '2025-03-11',
 '2020-06-11',
 '2026-02-17',
 '2025-07-15',
 '2024-02-23',
 '2019-09-01',
 '2024-04-22',
 '2021-05-25',
 '2025-11-20',
 '2026-05-12',
 '2021-08-19',
 '2025-08-21',
 '2026-03-02',
 '2025-05-26',
 '2026-03-09',
 '2026-02-07',
 '2026-05-13',
 '2025-11-05',
 '2026-01-30',
 '2024-04-15',
 '2025-09-16',
 '2025-05-12',
 '2026-01-02',
 '2022-12-16',
 '2026-05-31',
 '2020-12-01',
 '2026-04-25',
 '2020-11-01',
 '2026-02-27',
 '2025-11-17',
 '2026-05-30',
 '2023-10-11',
 '2022-08-30',
 '2024-03-28',
 '2023-09-07',
 '2025-07-03',
 '2025-09-27',
 '2024-08-07',
 '2026-04-18',
 '2024-03-12',
 '2025-01-10',
 '2024-10-15',
 '2023-08-04',
 '2021-07-06',
 '2026-07-15',
 '2022-07-17',
 '2025-02-18',
 '2023-08-08',
 '2026-01-29',
 '2023-07-17',
 '2021-08-20',
 '2023-02-20',
 '2023-08-07',
 '2025-05-17',
 '2024-10-02',
 '2026-02-25',
 '2025-04-04',
 '2024-11-30',
 '2026-03-05',
 '2025-02-24',
 '2023-08-18',
 '2023-08-11',
 '2025-04-28',
 '2020-08-31',
 '2019-08-29',
 '2024-04-16',
 '2025-05-31',
 '2025-09-09',
 '2023-06-30',
 '2021-08-04',
 '2022-06-13',
 '2023-07-22',
 '2023-12-26',
 '2021-09-13',
 '2025-05-29',
 '2025-02-27',
 '2026-01-21',
 '2026-09-23',
 '2025-08-29',
 '2025-05-30',
 '2024-09-22',
 '2023-09-27',
 '2022-11-18',
 '2025-12-17',
 '2023-06-06',
 '2022-04-26',
 '2024-11-01',
 '2023-02-27',
 '2021-03-22',
 '2023-08-27',
 '2022-05-16',
 '2025-06-03',
 '2023-08-09',
 '2025-10-06',
 '2026-03-16',
 '2026-04-29',
 '2022-06-08',
 '2024-05-23',
 '2026-09-21',
 '2025-04-02',
 '2023-03-03',
 '2022-06-21',
 '2025-03-28',
 '2026-06-21',
 '2021-06-30',
 '2019-06-10',
 '2022-06-05',
 '2024-08-18',
 '2019-05-01',
 '2026-02-06',
 '2021-07-31',
 '2019-06-25',
 '2023-03-27',
 '2022-09-28',
 '2020-08-12',
 '2025-12-22',
 '2024-10-10',
 '2026-09-29',
 '2024-06-17',
 '2022-06-17',
 '2026-08-21',
 '2025-02-17',
 '2026-07-18',
 '2016-03-03',
 '2026-01-12',
 '2022-06-27',
 '2026-02-19',
 '2026-08-26',
 '2026-03-23',
 '2024-04-24',
 '2024-09-25',
 '2023-09-25',
 '2023-05-31',
 '2022-05-31',
 '2025-07-05',
 '2026-09-28',
 '2026-01-06',
 '2022-06-23',
 '2024-06-02',
 '2025-03-31',
 '2021-09-15',
 '2026-09-25',
 '2026-05-07',
 '2023-06-07',
 '2023-05-30',
 '2024-09-17',
 '2023-08-23',
 '2025-03-13',
 '2023-04-04',
 '2026-06-27',
 '2024-06-29',
 '2026-02-20',
 '2024-02-17',
 '2025-02-21',
 '2021-09-29',
 '2023-06-10',
 '2024-05-28',
 '2026-08-23',
 '2019-07-17',
 '2023-03-06',
 '2026-01-22',
 '2023-07-12',
 '2023-07-24',
 '2023-06-19',
 '2023-07-09',
 '2022-02-14',
 '2024-04-30',
 '2021-09-21',
 '2022-09-21',
 '2026-07-28',
 '2022-12-15',
 '2024-10-29',
 '2025-10-08',
 '2023-11-01',
 '2022-01-01',
 '2024-08-19',
 '2021-09-24',
 '2020-09-30',
 '2025-05-21',
 '2025-08-28',
 '2024-07-25',
 '2022-05-13',
 '2021-07-12',
 '2023-09-11',
 '2025-10-03',
 '2025-12-28',
 '2022-03-31',
 '2022-11-01',
 '2024-05-31',
 '2026-08-29',
 '2021-03-29',
 '2026-09-14',
 '2024-08-20',
 '2022-08-09',
 '2021-03-30',
 '2024-01-10',
 '2026-11-05',
 '2023-03-15',
 '2022-05-22',
 '2026-04-23',
 '2026-09-20',
 '2022-12-01',
 '2021-02-01',
 '2021-09-14',
 '2025-09-17',
 '2025-08-19',
 '2022-04-07',
 '2026-03-07',
 '2023-09-12',
 '2022-12-19',
 '2022-05-01',
 '2026-03-22',
 '2022-05-28',
 '2026-02-10',
 '2023-02-08',
 '2026-06-14',
 '2025-09-07',
 '2025-06-20',
 '2026-09-27',
 '2024-11-22',
 '2026-03-29',
 '2023-02-28',
 '2023-05-18',
 '2025-08-12',
 '2024-04-17',
 '2020-11-30',
 '2025-05-09',
 '2023-02-14',
 '2026-11-27',
 '2024-09-21',
 '2025-01-16',
 '2026-04-16',
 '2021-09-08',
 '2025-06-11',
 '2021-01-05',
 '2026-09-16',
 '2024-12-15',
 '2021-06-02',
 '2025-11-13',
 '2024-08-02',
 '2025-09-10',
 '2022-11-15',
 '2024-12-13',
 '2024-05-02',
 '2025-10-14',
 '2024-01-03',
 '2025-10-16',
 '2024-04-09',
 '2026-08-14',
 '2024-04-04',
 '2022-01-06',
 '2021-02-03',
 '2024-02-01',
 '2024-08-08',
 '2024-05-21',
 '2023-11-17',
 '2025-04-10',
 '2025-12-30',
 '2024-05-30',
 '2024-09-24',
 '2024-09-04',
 '2026-02-11',
 '2019-01-30',
 '2025-10-22',
 '2022-09-29',
 '2011-12-28',
 '2021-06-18',
 '2022-11-02',
 '2025-03-06',
 '2026-01-24',
 '2023-04-15',
 '2023-03-28',
 '2024-03-02',
 '2025-04-09',
 '2025-10-24',
 '2024-02-27',
 '2022-05-15',
 '2019-09-27',
 '2026-01-05',
 '2026-04-26',
 '2026-02-28',
 '2026-02-23',
 '2008-09-30',
 '2025-01-06',
 '2024-09-19',
 '2023-05-16',
 '2026-09-15',
 '2023-07-31',
 '2025-07-14',
 '2018-10-01',
 '2026-01-23',
 '2026-04-21',
 '2023-06-23',
 '2023-06-11',
 '2025-11-02',
 '2021-12-27',
 '2023-01-06',
 '2022-08-07',
 '2026-07-08',
 '2026-01-15',
 '2026-07-24',
 '2024-09-05',
 '2020-07-01',
 '2025-09-13',
 '2021-01-06',
 '2025-07-13',
 '2024-07-17',
 '2026-05-23',
 '2023-08-24',
 '2025-02-26',
 '2025-01-30',
 '2025-04-23',
 '2025-06-15',
 '2021-02-22',
 '2024-03-27',
 '2025-07-18',
 '2023-01-03',
 '2023-05-22',
 '2024-05-22',
 '2023-05-24',
 '2024-08-21',
 '2022-05-30',
 '2025-12-20',
 '2025-06-27',
 '2025-05-22',
 '2023-12-06',
 '2025-01-24',
 '2026-03-28',
 '2022-09-27',
 '2025-11-18',
 '2020-09-17',
 '2025-11-21',
 '2023-05-09',
 '2023-05-23',
 '2023-09-13',
 '2024-12-10',
 '2024-07-31',
 '2026-09-07',
 '2024-06-20',
 '2026-07-30',
 '2025-05-23',
 '2022-12-02',
 '2017-04-01',
 '2023-02-03',
 '2025-06-26',
 '2024-10-11',
 '2023-07-14',
 '2025-06-18',
 '2022-08-17',
 '2022-12-06',
 '2022-03-01',
 '2023-03-05',
 '2023-01-04',
 '2023-04-11',
 '2023-07-16',
 '2026-07-19',
 '2026-02-02',
 '2022-12-20',
 '2023-01-02',
 '2025-02-22',
 '2024-11-14',
 '2025-01-21',
 '2026-01-14',
 '2020-09-21',
 '2026-08-20',
 '2025-06-10',
 '2024-12-30',
 '2021-08-02',
 '2026-05-17',
 '2024-11-18',
 '2024-05-09',
 '2024-07-11',
 '2022-07-29',
 '2022-07-11',
 '2022-04-30',
 '2026-09-09',
 '2023-09-19',
 '2024-03-29',
 '2024-02-12',
 '2024-04-11',
 '2024-03-20',
 '2023-07-26',
 '2022-01-12',
 '2026-03-18',
 '2022-06-20',
 '2021-02-06',
 '2016-11-17',
 '2023-09-04',
 '2024-04-05',
 '2025-11-12',
 '2024-05-25',
 '2021-02-05',
 '2022-03-26',
 '2021-06-21',
 '2023-12-17',
 '2026-03-04',
 '2020-08-11',
 '2025-01-22',
 '2025-04-11',
 '2024-11-27',
 '2025-10-29',
 '2023-07-28',
 '2024-09-10',
 '2022-08-08',
 '2023-04-27',
 '2025-03-23',
 '2025-11-24',
 '2025-02-10',
 '2020-12-22',
 '2023-07-13',
 '2024-06-13',
 '2024-07-09',
 '2025-11-14',
 '2026-10-29',
 '2026-01-31',
 '2026-04-05',
 '2023-06-21',
 '2023-03-30',
 '2024-06-30',
 '2024-12-04',
 '2025-12-31',
 '2017-10-01',
 '2025-11-30',
 '2022-09-19',
 '2023-10-05',
 '2025-08-14',
 '2023-12-05',
 '2021-04-30',
 '2022-04-25',
 '2025-02-15',
 '2022-08-11',
 '2024-11-23',
 '2021-04-21',
 '2024-03-15',
 '2025-05-11',
 '2021-03-23',
 '2025-07-20',
 '2020-09-14',
 '2022-05-25',
 '2023-10-15',
 '2026-11-02',
 '2024-10-30',
 '2024-01-08',
 '2024-05-29',
 '2024-08-16',
 '2018-09-25',
 '2021-01-18',
 '2022-07-18',
 '2025-08-02',
 '2022-06-03',
 '2023-05-17',
 '2021-01-01',
 '2023-09-18',
 '2021-02-24',
 '2021-02-25',
 '2023-10-16',
 '2025-06-29',
 '2021-07-21',
 '2023-06-26',
 '2024-03-18',
 '2025-09-14',
 '2024-12-05',
 '2021-04-23',
 '2022-09-22',
 '2023-06-27',
 '2022-02-10',
 '2025-06-08',
 '2022-12-30',
 '2020-10-26',
 '2024-08-28',
 '2023-03-10',
 '2024-03-22',
 '2022-07-07',
 '2022-03-14',
 '2026-05-16',
 '2025-03-30',
 '2025-02-23',
 '2024-04-18',
 '2024-12-27',
 '2024-01-30',
 '2018-05-08',
 '2025-05-07',
 ...]

In [93]:
df['action_date'] = pd.to_datetime(df['action_date'], errors = 'coerce').dt.date
df['period_of_performance_start_date'] = pd.to_datetime(df['period_of_performance_start_date'], errors = 'coerce').dt.date
df['period_of_performance_current_end_date'] = pd.to_datetime(df['period_of_performance_current_end_date'], errors = 'coerce').dt.date

In [94]:
df['action_date'].head()

0    2026-06-04
1    2026-06-04
2    2026-06-04
3    2026-06-04
4    2026-06-04
Name: action_date, dtype: object

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 774934 entries, 0 to 774933
Data columns (total 32 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   contract_award_unique_key                  774934 non-null  str
 1   award_id_piid                              774934 non-null  str
 2   federal_action_obligation                  774934 non-null  float64
 3   total_dollars_obligated                    774934 non-null  float64
 4   action_date                                774934 non-null  object
 5   action_date_fiscal_year                    774934 non-null  int64
 6   period_of_performance_start_date           774934 non-null  object
 7   period_of_performance_current_end_date     774702 non-null  object
 8   transaction_description                    774923 non-null  str
 9   award_type                                 774702 non-null  str
 10  type_of_contract_pricing                   774934 non-null  str
 11  extent_competed                            774934 non-null  str
 12  number_of_offers_received                  228234 non-null  float64
 13  awarding_agency_name                       774934 non-null  str
 14  awarding_sub_agency_name                   774934 non-null  str
 15  funding_agency_name                        774934 non-null  str
 16  recipient_uei                              774934 non-null  str
 17  recipient_name                             774934 non-null  str
 18  recipient_city_name                        774934 non-null  str
 19  recipient_state_name                       769472 non-null  str
 20  recipient_country_name                     774934 non-null  str
 21  primary_place_of_performance_city_name     758466 non-null  str
 22  primary_place_of_performance_state_name    758481 non-null  str
 23  primary_place_of_performance_country_name  774702 non-null  str
 24  naics_code                                 774934 non-null  float64
 25  naics_description                          774934 non-null  str
 26  product_or_service_code                    774934 non-null  str
 27  product_or_service_code_description        774934 non-null  str
 28  veteran_owned_business                     774934 non-null  str
 29  woman_owned_business                       774934 non-null  str
 30  minority_owned_business                    774934 non-null  str
 31  small_disadvantaged_business               774934 non-null  str
dtypes: float64(4), int64(1), object(3), str(24)
memory usage: 189.2+ MB

In [96]:
## CONTRACTS

def get_agency_id(agency, sub_agency, funding):
    key = (agency, sub_agency, funding)
    return agency_map.get(key)

def get_recipient_id(uei):
    if pd.isna(uei):
        return None
    return recipients_map.get(uei)

def get_location_id(city, state, country, loc_type):
    key = (city if pd.notna(city) else None,
          state if pd.notna(state) else None,
          country if pd.notna(country) else None,
          loc_type)
    return locs_map.get(key)

In [100]:
batch = []
batch_size = 1000

for index, row in df.iterrows():
    batch.append((row['contract_award_unique_key'] if pd.notna(row['contract_award_unique_key']) else None,
        row['award_id_piid'] if pd.notna(row['award_id_piid']) else None,
        get_agency_id(row['awarding_agency_name'], row['awarding_sub_agency_name'], row['funding_agency_name']),
        get_recipient_id(row['recipient_uei']),
        get_location_id(row['recipient_city_name'], row['recipient_state_name'], row['recipient_country_name'], 'recipient'),
        get_location_id(row['primary_place_of_performance_city_name'], row['primary_place_of_performance_state_name'], row['primary_place_of_performance_country_name'], 'performance'),
        float(row['federal_action_obligation']) if pd.notna(row['federal_action_obligation']) else None,
        float(row['total_dollars_obligated']) if pd.notna(row['total_dollars_obligated']) else None,
        row['action_date'],
        int(row['action_date_fiscal_year']) if pd.notna(row['action_date_fiscal_year']) else None,
        row['period_of_performance_start_date'],
        row['period_of_performance_current_end_date'],
        row['transaction_description'] if pd.notna(row['transaction_description']) else None,
        row['award_type'] if pd.notna(row['award_type']) else None,
        row['type_of_contract_pricing'] if pd.notna(row['type_of_contract_pricing']) else None,
        row['extent_competed'] if pd.notna(row['extent_competed']) else None,
        int(row['number_of_offers_received']) if pd.notna(row['number_of_offers_received']) else None,
        row['naics_code'] if pd.notna(row['naics_code']) else None,
        row['naics_description'] if pd.notna(row['naics_description']) else None,
        row['product_or_service_code'] if pd.notna(row['product_or_service_code']) else None,
        row['product_or_service_code_description'] if pd.notna(row['product_or_service_code_description']) else None,
    ))

    if len(batch) == batch_size:
        cursor.executemany("""
        INSERT INTO contracts(contract_award_unique_key, award_id_piid, agency_id, recipient_id, recipient_location_id, 
                                performance_location_id, federal_action_obligation, total_dollars_obligated,
                                action_date, action_date_fiscal_year, period_of_performance_start_date, 
                                period_of_performance_current_end_date, transaction_description, award_type, 
                                type_of_contract_pricing, extent_competed, number_of_offers_received, 
                                naics_code, naics_description, 
                                product_or_service_code, product_or_service_code_description)
        
        VALUE(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""", batch)
        conn.commit()
        batch = []
if batch:
    cursor.executemany("""
        INSERT INTO contracts (
            contract_award_unique_key, award_id_piid,
            agency_id, recipient_id,
            recipient_location_id, performance_location_id,
            federal_action_obligation, total_dollars_obligated,
            action_date, action_date_fiscal_year,
            period_of_performance_start_date, period_of_performance_current_end_date,
            transaction_description, award_type,
            type_of_contract_pricing, extent_competed,
            number_of_offers_received, naics_code,
            naics_description, product_or_service_code,
            product_or_service_code_description
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, batch)
    conn.commit()

In [101]:
cursor.close()
conn.close()