In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/ahishekanand/Desktop/Portfolio Project/raw_data/FY2026_All_Contracts_Full_20260610_1.csv")

C:\Users\ahishekanand\AppData\Local\Temp\ipykernel_3988\927320455.py:1: DtypeWarning: Columns (0: parent_award_agency_id, 1: sam_exception_description, 2: recipient_zip_4_code, 3: recipient_phone_number, 4: recipient_fax_number, 5: primary_place_of_performance_zip_4, 6: type_of_idc_code, 7: type_of_idc, 8: dod_claimant_program_code, 9: dod_claimant_program_description, 10: dod_acquisition_program_code, 11: dod_acquisition_program_description, 12: information_technology_commercial_item_category_code, 13: information_technology_commercial_item_category, 14: research_code, 15: research, 16: other_statutory_authority, 17: program_acronym, 18: national_interest_action_code, 19: national_interest_action, 20: sea_transportation_code, 21: sea_transportation) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/ahishekanand/Desktop/Portfolio Project/raw_data/FY2026_All_Contracts_Full_20260610_1.csv")

In [6]:
df.shape

(1000000, 297)

In [7]:
df.head()

,contract_transaction_unique_key,contract_award_unique_key,award_id_piid,modification_number,transaction_number,parent_award_agency_id,parent_award_agency_name,parent_award_id_piid,parent_award_modification_number,federal_action_obligation,...,highly_compensated_officer_2_amount,highly_compensated_officer_3_name,highly_compensated_officer_3_amount,highly_compensated_officer_4_name,highly_compensated_officer_4_amount,highly_compensated_officer_5_name,highly_compensated_officer_5_amount,usaspending_permalink,initial_report_date,last_modified_date
0,12C2_-NONE-_1202RZ25T0088_P00002_-NONE-_-NONE-,CONT_IDV_1202RZ25T0088_12C2,1202RZ25T0088,P00002,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_IDV_120...,2026-06-04 11:29:20+00,2026-06-04 11:34:02+00
1,4732_-NONE-_47QTCA19D00MJ_PA0021_-NONE-_-NONE-,CONT_IDV_47QTCA19D00MJ_4732,47QTCA19D00MJ,PA0021,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_IDV_47Q...,2026-06-04 06:39:48+00,2026-06-04 06:39:51+00
2,7008_-NONE-_70Z03125CALAM0008_P00003_-NONE-_0,CONT_AWD_70Z03125CALAM0008_7008_-NONE-_-NONE-,70Z03125CALAM0008,P00003,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_70Z...,2026-06-04 11:59:18+00,2026-06-04 12:17:18+00
3,7008_-NONE-_70Z03826PF0000382_0_-NONE-_0,CONT_AWD_70Z03826PF0000382_7008_-NONE-_-NONE-,70Z03826PF0000382,0,0.0,NaN,NaN,NaN,NaN,8525.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_70Z...,2026-06-04 06:25:00+00,2026-06-04 06:29:29+00
4,7014_7014_70B06C26F00000124_P00001_70B06C24A00...,CONT_AWD_70B06C26F00000124_7014_70B06C24A00000...,70B06C26F00000124,P00001,0.0,7014,U.S. CUSTOMS AND BORDER PROTECTION,70B06C24A00000049,P00003,210405.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.usaspending.gov/award/CONT_AWD_70B...,2026-06-03 15:14:34+00,2026-06-04 12:08:58+00

In [8]:
df.columns.tolist()

['contract_transaction_unique_key',
 'contract_award_unique_key',
 'award_id_piid',
 'modification_number',
 'transaction_number',
 'parent_award_agency_id',
 'parent_award_agency_name',
 'parent_award_id_piid',
 'parent_award_modification_number',
 'federal_action_obligation',
 'total_dollars_obligated',
 'total_outlayed_amount_for_overall_award',
 'base_and_exercised_options_value',
 'current_total_value_of_award',
 'base_and_all_options_value',
 'potential_total_value_of_award',
 'disaster_emergency_fund_codes_for_overall_award',
 'outlayed_amount_from_COVID-19_supplementals_for_overall_award',
 'obligated_amount_from_COVID-19_supplementals_for_overall_award',
 'outlayed_amount_from_IIJA_supplemental_for_overall_award',
 'obligated_amount_from_IIJA_supplemental_for_overall_award',
 'action_date',
 'action_date_fiscal_year',
 'period_of_performance_start_date',
 'period_of_performance_current_end_date',
 'period_of_performance_potential_end_date',
 'ordering_period_end_date',
 'solicitation_date',
 'awarding_agency_code',
 'awarding_agency_name',
 'awarding_sub_agency_code',
 'awarding_sub_agency_name',
 'awarding_office_code',
 'awarding_office_name',
 'funding_agency_code',
 'funding_agency_name',
 'funding_sub_agency_code',
 'funding_sub_agency_name',
 'funding_office_code',
 'funding_office_name',
 'treasury_accounts_funding_this_award',
 'federal_accounts_funding_this_award',
 'object_classes_funding_this_award',
 'program_activities_funding_this_award',
 'foreign_funding',
 'foreign_funding_description',
 'sam_exception',
 'sam_exception_description',
 'recipient_uei',
 'recipient_duns',
 'recipient_name',
 'recipient_name_raw',
 'recipient_doing_business_as_name',
 'cage_code',
 'recipient_parent_uei',
 'recipient_parent_duns',
 'recipient_parent_name',
 'recipient_parent_name_raw',
 'recipient_country_code',
 'recipient_country_name',
 'recipient_address_line_1',
 'recipient_address_line_2',
 'recipient_city_name',
 'prime_award_transaction_recipient_county_fips_code',
 'recipient_county_name',
 'prime_award_transaction_recipient_state_fips_code',
 'recipient_state_code',
 'recipient_state_name',
 'recipient_zip_4_code',
 'prime_award_transaction_recipient_cd_original',
 'prime_award_transaction_recipient_cd_current',
 'recipient_phone_number',
 'recipient_fax_number',
 'primary_place_of_performance_country_code',
 'primary_place_of_performance_country_name',
 'primary_place_of_performance_city_name',
 'prime_award_transaction_place_of_performance_county_fips_code',
 'primary_place_of_performance_county_name',
 'prime_award_transaction_place_of_performance_state_fips_code',
 'primary_place_of_performance_state_code',
 'primary_place_of_performance_state_name',
 'primary_place_of_performance_zip_4',
 'prime_award_transaction_place_of_performance_cd_original',
 'prime_award_transaction_place_of_performance_cd_current',
 'award_or_idv_flag',
 'award_type_code',
 'award_type',
 'idv_type_code',
 'idv_type',
 'multiple_or_single_award_idv_code',
 'multiple_or_single_award_idv',
 'type_of_idc_code',
 'type_of_idc',
 'type_of_contract_pricing_code',
 'type_of_contract_pricing',
 'transaction_description',
 'prime_award_base_transaction_description',
 'action_type_code',
 'action_type',
 'solicitation_identifier',
 'number_of_actions',
 'inherently_governmental_functions',
 'inherently_governmental_functions_description',
 'product_or_service_code',
 'product_or_service_code_description',
 'contract_bundling_code',
 'contract_bundling',
 'dod_claimant_program_code',
 'dod_claimant_program_description',
 'naics_code',
 'naics_description',
 'recovered_materials_sustainability_code',
 'recovered_materials_sustainability',
 'domestic_or_foreign_entity_code',
 'domestic_or_foreign_entity',
 'dod_acquisition_program_code',
 'dod_acquisition_program_description',
 'information_technology_commercial_item_category_code',
 'information_technology_commercial_item_category',
 'epa_designated_product_code',
 'epa_designated_product',
 'country_of_product_or_service_origin_code',
 'country_of_product_or_service_origin',
 'place_of_manufacture_code',
 'place_of_manufacture',
 'subcontracting_plan_code',
 'subcontracting_plan',
 'extent_competed_code',
 'extent_competed',
 'solicitation_procedures_code',
 'solicitation_procedures',
 'type_of_set_aside_code',
 'type_of_set_aside',
 'evaluated_preference_code',
 'evaluated_preference',
 'research_code',
 'research',
 'fair_opportunity_limited_sources_code',
 'fair_opportunity_limited_sources',
 'other_than_full_and_open_competition_code',
 'other_than_full_and_open_competition',
 'number_of_offers_received',
 'commercial_item_acquisition_procedures_code',
 'commercial_item_acquisition_procedures',
 'small_business_competitiveness_demonstration_program',
 'simplified_procedures_for_certain_commercial_items_code',
 'simplified_procedures_for_certain_commercial_items',
 'a76_fair_act_action_code',
 'a76_fair_act_action',
 'fed_biz_opps_code',
 'fed_biz_opps',
 'local_area_set_aside_code',
 'local_area_set_aside',
 'price_evaluation_adjustment_preference_percent_difference',
 'clinger_cohen_act_planning_code',
 'clinger_cohen_act_planning',
 'materials_supplies_articles_equipment_code',
 'materials_supplies_articles_equipment',
 'labor_standards_code',
 'labor_standards',
 'construction_wage_rate_requirements_code',
 'construction_wage_rate_requirements',
 'interagency_contracting_authority_code',
 'interagency_contracting_authority',
 'other_statutory_authority',
 'program_acronym',
 'parent_award_type_code',
 'parent_award_type',
 'parent_award_single_or_multiple_code',
 'parent_award_single_or_multiple',
 'major_program',
 'national_interest_action_code',
 'national_interest_action',
 'cost_or_pricing_data_code',
 'cost_or_pricing_data',
 'cost_accounting_standards_clause_code',
 'cost_accounting_standards_clause',
 'government_furnished_property_code',
 'government_furnished_property',
 'sea_transportation_code',
 'sea_transportation',
 'undefinitized_action_code',
 'undefinitized_action',
 'consolidated_contract_code',
 'consolidated_contract',
 'performance_based_service_acquisition_code',
 'performance_based_service_acquisition',
 'multi_year_contract_code',
 'multi_year_contract',
 'contract_financing_code',
 'contract_financing',
 'purchase_card_as_payment_method_code',
 'purchase_card_as_payment_method',
 'contingency_humanitarian_or_peacekeeping_operation_code',
 'contingency_humanitarian_or_peacekeeping_operation',
 'alaskan_native_corporation_owned_firm',
 'american_indian_owned_business',
 'indian_tribe_federally_recognized',
 'native_hawaiian_organization_owned_firm',
 'tribally_owned_firm',
 'veteran_owned_business',
 'service_disabled_veteran_owned_business',
 'woman_owned_business',
 'women_owned_small_business',
 'economically_disadvantaged_women_owned_small_business',
 'joint_venture_women_owned_small_business',
 'joint_venture_economic_disadvantaged_women_owned_small_bus',
 'minority_owned_business',
 'subcontinent_asian_asian_indian_american_owned_business',
 'asian_pacific_american_owned_business',
 'black_american_owned_business',
 'hispanic_american_owned_business',
 'native_american_owned_business',
 'other_minority_owned_business',
 'contracting_officers_determination_of_business_size',
 'contracting_officers_determination_of_business_size_code',
 'emerging_small_business',
 'community_developed_corporation_owned_firm',
 'labor_surplus_area_firm',
 'us_federal_government',
 'federally_funded_research_and_development_corp',
 'federal_agency',
 'us_state_government',
 'us_local_government',
 'city_local_government',
 'county_local_government',
 'inter_municipal_local_government',
 'local_government_owned',
 'municipality_local_government',
 'school_district_local_government',
 'township_local_government',
 'us_tribal_government',
 'foreign_government',
 'organizational_type',
 'corporate_entity_not_tax_exempt',
 'corporate_entity_tax_exempt',
 'partnership_or_limited_liability_partnership',
 'sole_proprietorship',
 'small_agricultural_cooperative',
 'international_organization',
 'us_government_entity',
 'community_development_corporation',
 'domestic_shelter',
 'educational_institution',
 'foundation',
 'hospital_flag',
 'manufacturer_of_goods',
 'veterinary_hospital',
 'hispanic_servicing_institution',
 'receives_contracts',
 'receives_financial_assistance',
 'receives_contracts_and_financial_assistance',
 'airport_authority',
 'council_of_governments',
 'housing_authorities_public_tribal',
 'interstate_entity',
 'planning_commission',
 'port_authority',
 'transit_authority',
 'subchapter_scorporation',
 'limited_liability_corporation',
 'foreign_owned',
 'for_profit_organization',
 'nonprofit_organization',
 'other_not_for_profit_organization',
 'the_ability_one_program',
 'private_university_or_college',
 'state_controlled_institution_of_higher_learning',
 '1862_land_grant_college',
 '1890_land_grant_college',
 '1994_land_grant_college',
 'minority_institution',
 'historically_black_college',
 'tribal_college',
 'alaskan_native_servicing_institution',
 'native_hawaiian_servicing_institution',
 'school_of_forestry',
 'veterinary_college',
 'dot_certified_disadvantage',
 'self_certified_small_disadvantaged_business',
 'small_disadvantaged_business',
 'c8a_program_participant',
 'historically_underutilized_business_zone_hubzone_firm',
 'sba_certified_8a_joint_venture',
 'highly_compensated_officer_1_name',
 'highly_compensated_officer_1_amount',
 'highly_compensated_officer_2_name',
 'highly_compensated_officer_2_amount',
 'highly_compensated_officer_3_name',
 'highly_compensated_officer_3_amount',
 'highly_compensated_officer_4_name',
 'highly_compensated_officer_4_amount',
 'highly_compensated_officer_5_name',
 'highly_compensated_officer_5_amount',
 'usaspending_permalink',
 'initial_report_date',
 'last_modified_date']

In [9]:
columns_to_keep = [
    'contract_award_unique_key',
    'award_id_piid',
    'federal_action_obligation',
    'total_dollars_obligated',
    'action_date',
    'action_date_fiscal_year',
    'period_of_performance_start_date',
    'period_of_performance_current_end_date',
    'transaction_description',
    'award_type',
    'type_of_contract_pricing',
    'extent_competed',
    'number_of_offers_received',
    'awarding_agency_name',
    'awarding_sub_agency_name',
    'funding_agency_name',
    'recipient_uei',
    'recipient_name',
    'recipient_city_name',
    'recipient_state_name',
    'recipient_country_name',
    'primary_place_of_performance_city_name',
    'primary_place_of_performance_state_name',
    'primary_place_of_performance_country_name',
    'naics_code',
    'naics_description',
    'product_or_service_code',
    'product_or_service_code_description',
    'veteran_owned_business',
    'woman_owned_business',
    'minority_owned_business',
    'small_disadvantaged_business',
]

df = df[columns_to_keep]

In [10]:
df.head()

,contract_award_unique_key,award_id_piid,federal_action_obligation,total_dollars_obligated,action_date,action_date_fiscal_year,period_of_performance_start_date,period_of_performance_current_end_date,transaction_description,award_type,...,primary_place_of_performance_state_name,primary_place_of_performance_country_name,naics_code,naics_description,product_or_service_code,product_or_service_code_description,veteran_owned_business,woman_owned_business,minority_owned_business,small_disadvantaged_business
0,CONT_IDV_1202RZ25T0088_12C2,1202RZ25T0088,0.0,0.0,2026-06-04,2026,2025-05-01,NaN,DURANGO TANKER BASE HELICOPTER LANDING AREA AG...,NaN,...,NaN,NaN,115310.0,SUPPORT ACTIVITIES FOR FORESTRY,F099,NATURAL RESOURCES/CONSERVATION- OTHER,f,f,f,f
1,CONT_IDV_47QTCA19D00MJ_4732,47QTCA19D00MJ,0.0,0.0,2026-06-04,2026,2019-09-26,NaN,FEDERAL SUPPLY SCHEDULE CONTRACT,NaN,...,NaN,NaN,541519.0,OTHER COMPUTER RELATED SERVICES,D399,IT AND TELECOM- OTHER IT AND TELECOMMUNICATIONS,f,f,f,f
2,CONT_AWD_70Z03125CALAM0008_7008_-NONE-_-NONE-,70Z03125CALAM0008,0.0,91190.0,2026-06-04,2026,2025-09-14,2026-07-31,REPLACE FLOORING AND REMODEL KITCHEN AND COMMS...,DEFINITIVE CONTRACT,...,CALIFORNIA,UNITED STATES,238330.0,FLOORING CONTRACTORS,Z1AZ,MAINTENANCE OF OTHER ADMINISTRATIVE FACILITIES...,t,f,t,f
3,CONT_AWD_70Z03826PF0000382_7008_-NONE-_-NONE-,70Z03826PF0000382,8525.7,8525.7,2026-06-04,2026,2026-06-04,2027-08-28,"PROCUREMENT OF SPARE ROD, BALL BEARING TO BE U...",PURCHASE ORDER,...,TEXAS,UNITED STATES,336413.0,OTHER AIRCRAFT PARTS AND AUXILIARY EQUIPMENT M...,3110,"BEARINGS, ANTIFRICTION, UNMOUNTED",f,f,f,f
4,CONT_AWD_70B06C26F00000124_7014_70B06C24A00000...,70B06C26F00000124,210405.6,3013141.3,2026-06-04,2026,2026-05-19,2027-05-18,THE PURPOSE OF THIS MODIFICATION IS TO INCORPO...,BPA CALL,...,VIRGINIA,UNITED STATES,541611.0,ADMINISTRATIVE MANAGEMENT AND GENERAL MANAGEME...,R425,SUPPORT- PROFESSIONAL: ENGINEERING/TECHNICAL,f,f,f,f

In [11]:
df.shape

(1000000, 32)

In [12]:
df = df[df['federal_action_obligation'] > 0]

In [13]:
df.shape

(825514, 32)

In [14]:
df['awarding_agency_name'].value_counts().head(10)

awarding_agency_name
General Services Administration            426467
Department of Defense                      302775
Department of Justice                       19370
Department of Veterans Affairs              18870
Department of Homeland Security              7452
Department of the Interior                   7298
Department of State                          6641
Department of Agriculture                    6573
Department of Health and Human Services      6400
Department of Transportation                 5698
Name: count, dtype: int64

In [15]:
top_5_agencies = ["General Services Administration", "Department of Defense", "Department of Justice", 
                    "Department of Veterans Affairs", "Department of Homeland Security"]

In [16]:
df = df[df['awarding_agency_name'].isin(top_5_agencies)]

In [17]:
df.shape

(774934, 32)

In [18]:
df = df.dropna(subset = 'recipient_name')

In [19]:
df.shape

(774934, 32)

In [20]:
df.to_csv('cleaned_contracts.csv', index = False)

In [33]:
df['contract_award_unique_key'].unique()

<StringArray>
[         'CONT_AWD_70Z03826PF0000382_7008_-NONE-_-NONE-',
 'CONT_AWD_70B06C26F00000124_7014_70B06C24A00000049_7014',
         'CONT_AWD_47PD5426F0168_4740_47PG5226A0007_4740',
              'CONT_AWD_36C24526P0440_3600_-NONE-_-NONE-',
     'CONT_AWD_15B20726F00000108_1540_36W79720D0001_3600',
          'CONT_AWD_70B02C25P00000272_7014_-NONE-_-NONE-',
              'CONT_AWD_36C26025P0533_3600_-NONE-_-NONE-',
 'CONT_AWD_70Z03826FA0000109_7008_70Z03826DL0000001_7008',
        'CONT_AWD_70Z07925FALD00002_7008_GS10F0318T_4730',
              'CONT_AWD_36C26326P0505_3600_-NONE-_-NONE-',
 ...
         'CONT_AWD_SPE2DR26F3VNV_9700_SPE2DR25D2104_9700',
         'CONT_AWD_SPE2DR26F6C48_9700_SPE2DR25D3101_9700',
         'CONT_AWD_SPE2DR26F7PJD_9700_SPE2DR25D7059_9700',
         'CONT_AWD_SPE2DR26FVYT1_9700_SPE2DR25D3002_9700',
         'CONT_AWD_SPE2DV26F9RY6_9700_SPE2DV17D1047_9700',
         'CONT_AWD_SPE30026FYTT5_9700_SPE30023D4111_9700',
         'CONT_AWD_SPE3SU26F8FTJ_9700_SPE30023DS404_9700',
         'CONT_AWD_SPE3SU26F8HG1_9700_SPE30026DS448_9700',
         'CONT_AWD_SPE3SU26F8HWW_9700_SPE30023DS409_9700',
         'CONT_AWD_SPE3SU26F8K8J_9700_SPE30025DSA27_9700']
Length: 765458, dtype: str